
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class AddService
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox combocourse;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtprice;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox combostate;

		private global::Gtk.Button btnAddService;

		private global::Gtk.Entry txtname;

		private global::Gtk.Label label1;

		private global::Gtk.Label label7;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.AddService
			this.Name = "escuela_manejo.Main_forms.AddService";
			this.Title = global::Mono.Unix.Catalog.GetString("AddService");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.AddService.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Servicio");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w1.X = 150;
			w1.Y = 7;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Curso");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w2.X = 40;
			w2.Y = 108;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.combocourse = global::Gtk.ComboBox.NewText();
			this.combocourse.Name = "combocourse";
			this.fixed1.Add(this.combocourse);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combocourse]));
			w3.X = 122;
			w3.Y = 104;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Precio");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w4.X = 33;
			w4.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("$");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w5.X = 119;
			w5.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtprice = new global::Gtk.Entry();
			this.txtprice.CanFocus = true;
			this.txtprice.Name = "txtprice";
			this.txtprice.IsEditable = true;
			this.txtprice.InvisibleChar = '•';
			this.fixed1.Add(this.txtprice);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtprice]));
			w6.X = 141;
			w6.Y = 200;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w7.X = 32;
			w7.Y = 250;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.combostate = global::Gtk.ComboBox.NewText();
			this.combostate.AppendText(global::Mono.Unix.Catalog.GetString("Seleccione..."));
			this.combostate.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.combostate.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.combostate.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.combostate.Name = "combostate";
			this.fixed1.Add(this.combostate);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combostate]));
			w8.X = 118;
			w8.Y = 245;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAddService = new global::Gtk.Button();
			this.btnAddService.CanFocus = true;
			this.btnAddService.Name = "btnAddService";
			this.btnAddService.UseUnderline = true;
			this.btnAddService.Label = global::Mono.Unix.Catalog.GetString("Agregar Servicio");
			this.fixed1.Add(this.btnAddService);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAddService]));
			w9.X = 131;
			w9.Y = 300;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtname = new global::Gtk.Entry();
			this.txtname.CanFocus = true;
			this.txtname.Name = "txtname";
			this.txtname.IsEditable = true;
			this.txtname.InvisibleChar = '•';
			this.fixed1.Add(this.txtname);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtname]));
			w10.X = 121;
			w10.Y = 61;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre ");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w11.X = 28;
			w11.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Si no es un curso no seleccionar");
			this.fixed1.Add(this.label7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
			w12.X = 122;
			w12.Y = 156;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 407;
			this.DefaultHeight = 351;
			this.Show();
			this.btnAddService.Clicked += new global::System.EventHandler(this.onClickBtnAddService);
		}
	}
}
