
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class AddCourseInstance
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label8;

		private global::Gtk.ComboBox combocourse;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label9;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox10;

		private global::Gtk.ComboBox comboins;

		private global::Gtk.ComboBox comboveh;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vbox8;

		private global::Gtk.ComboBox comboclient;

		private global::Gtk.Calendar calenIni;

		private global::Gtk.Calendar calenEnd;

		private global::Gtk.Button button4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.AddCourseInstance
			this.Name = "escuela_manejo.Main_forms.AddCourseInstance";
			this.Title = global::Mono.Unix.Catalog.GetString("AddCourseInstance");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.AddCourseInstance.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo de curso:");
			this.hbox4.Add(this.label8);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label8]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.combocourse = global::Gtk.ComboBox.NewText();
			this.combocourse.WidthRequest = 300;
			this.combocourse.Name = "combocourse";
			this.hbox4.Add(this.combocourse);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.combocourse]));
			w2.Position = 1;
			w2.Fill = false;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString(" Instructor :      ");
			this.vbox11.Add(this.label9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label9]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString(" Vehiculo:");
			this.vbox11.Add(this.label10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label10]));
			w5.Position = 1;
			this.hbox5.Add(this.vbox11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox11]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.comboins = global::Gtk.ComboBox.NewText();
			this.comboins.WidthRequest = 300;
			this.comboins.Name = "comboins";
			this.vbox10.Add(this.comboins);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.comboins]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.comboveh = global::Gtk.ComboBox.NewText();
			this.comboveh.Name = "comboveh";
			this.vbox10.Add(this.comboveh);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.comboveh]));
			w8.Position = 1;
			w8.Fill = false;
			this.hbox5.Add(this.vbox10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox10]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha inicial");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w11.X = 15;
			w11.Y = 140;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha final");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w12.X = 8;
			w12.Y = 310;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Cliente");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w13.X = 15;
			w13.Y = 10;
			this.hbox6.Add(this.fixed1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.fixed1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.comboclient = global::Gtk.ComboBox.NewText();
			this.comboclient.WidthRequest = 300;
			this.comboclient.Name = "comboclient";
			this.vbox8.Add(this.comboclient);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.comboclient]));
			w15.Position = 0;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.calenIni = new global::Gtk.Calendar();
			this.calenIni.CanFocus = true;
			this.calenIni.Name = "calenIni";
			this.calenIni.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox8.Add(this.calenIni);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.calenIni]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.calenEnd = new global::Gtk.Calendar();
			this.calenEnd.CanFocus = true;
			this.calenEnd.Name = "calenEnd";
			this.calenEnd.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox8.Add(this.calenEnd);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.calenEnd]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox6.Add(this.vbox8);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox8]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Agregar Instancia");
			this.vbox7.Add(this.button4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button4]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 459;
			this.DefaultHeight = 580;
			this.Show();
			this.button4.Clicked += new global::System.EventHandler(this.onClickBtnAddService);
		}
	}
}
