
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Security_forms
{
	public partial class SecurityAddRol
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label lbrol;

		private global::Gtk.Entry txtrol;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox comborol;

		private global::Gtk.Button button6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Security_forms.SecurityAddRol
			this.Name = "escuela_manejo.Security_forms.SecurityAddRol";
			this.Title = global::Mono.Unix.Catalog.GetString("SecurityAddRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Security_forms.SecurityAddRol.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.hbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lbrol = new global::Gtk.Label();
			this.lbrol.Name = "lbrol";
			this.lbrol.LabelProp = global::Mono.Unix.Catalog.GetString("Rol");
			this.hbox4.Add(this.lbrol);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lbrol]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtrol = new global::Gtk.Entry();
			this.txtrol.CanFocus = true;
			this.txtrol.Name = "txtrol";
			this.txtrol.IsEditable = true;
			this.txtrol.InvisibleChar = '•';
			this.hbox4.Add(this.txtrol);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtrol]));
			w3.Position = 1;
			this.hbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox4]));
			w4.Position = 1;
			this.vbox4.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.comborol = global::Gtk.ComboBox.NewText();
			this.comborol.WidthRequest = 150;
			this.comborol.Name = "comborol";
			this.hbox3.Add(this.comborol);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.comborol]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox4.Add(this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Agregar rol");
			this.vbox4.Add(this.button6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button6]));
			w9.Position = 2;
			w9.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button6.Clicked += new global::System.EventHandler(this.OnBtnAgregarRolClicked);
		}
	}
}
