
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class Window
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.DrawingArea drawingarea1;

		private global::Gtk.Image image2;

		private global::Gtk.Button button1;

		private global::Gtk.Button button3;

		private global::Gtk.Button button2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.Window
			this.WidthRequest = 600;
			this.HeightRequest = 300;
			this.Name = "escuela_manejo.Main_forms.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu Principal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultHeight = 500;
			// Container child escuela_manejo.Main_forms.Window.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 500;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.drawingarea1 = new global::Gtk.DrawingArea();
			this.drawingarea1.Name = "drawingarea1";
			this.fixed1.Add(this.drawingarea1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.drawingarea1]));
			w1.X = 234;
			w1.Y = 99;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image();
			this.image2.WidthRequest = 144;
			this.image2.HeightRequest = 144;
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("escuela_manejo.driving-144.png");
			this.fixed1.Add(this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image2]));
			w2.X = 437;
			w2.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 200;
			this.button1.HeightRequest = 0;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Cursos");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w3.X = 28;
			w3.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.WidthRequest = 200;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Pagos");
			this.fixed1.Add(this.button3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
			w4.X = 28;
			w4.Y = 113;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.WidthRequest = 200;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Seguridad");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w5.X = 28;
			w5.Y = 172;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 675;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.OnButtonCoursesClicked);
		}
	}
}
