
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class AddCourse
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entryName;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entryDes;

		private global::Gtk.VBox vbox7;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Button button2;

		private global::Gtk.Button ClearEntry;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.AddCourse
			this.Name = "escuela_manejo.Main_forms.AddCourse";
			this.Title = global::Mono.Unix.Catalog.GetString("AddCourse");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.AddCourse.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre del nuevo curso");
			this.hbox5.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryName = new global::Gtk.Entry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '•';
			this.hbox5.Add(this.entryName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryName]));
			w2.Position = 1;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion del nuevo curso");
			this.hbox6.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryDes = new global::Gtk.Entry();
			this.entryDes.CanFocus = true;
			this.entryDes.Name = "entryDes";
			this.entryDes.IsEditable = true;
			this.entryDes.InvisibleChar = '•';
			this.hbox6.Add(this.entryDes);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryDes]));
			w5.Position = 1;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox3.Add(this.vbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Agregar Curso");
			this.vbox8.Add(this.button2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.button2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox3.Add(this.vbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox7]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ClearEntry = new global::Gtk.Button();
			this.ClearEntry.CanFocus = true;
			this.ClearEntry.Name = "ClearEntry";
			this.ClearEntry.UseUnderline = true;
			this.ClearEntry.Label = global::Mono.Unix.Catalog.GetString("Limpiar campos");
			this.vbox3.Add(this.ClearEntry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.ClearEntry]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 370;
			this.DefaultHeight = 300;
			this.Show();
			this.button2.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.ClearEntry.Clicked += new global::System.EventHandler(this.onClickBtnClean);
		}
	}
}
