
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class VehicleAdmin
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtcategory;

		private global::Gtk.Entry txtmodel;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtbrand;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtplate;

		private global::Gtk.Entry txtcolor;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox statecombo;

		private global::Gtk.Entry txtbuscar;

		private global::Gtk.Button button1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView vehitreeview;

		private global::Gtk.Button button2;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Button button5;

		private global::Gtk.Button button6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.VehicleAdmin
			this.Name = "escuela_manejo.Main_forms.VehicleAdmin";
			this.Title = global::Mono.Unix.Catalog.GetString("Vehicle");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.VehicleAdmin.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Vehiculos");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 236;
			w1.Y = 17;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Categoria:");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 35;
			w2.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Modelo:");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w3.X = 35;
			w3.Y = 115;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtcategory = new global::Gtk.Entry();
			this.txtcategory.CanFocus = true;
			this.txtcategory.Name = "txtcategory";
			this.txtcategory.IsEditable = true;
			this.txtcategory.InvisibleChar = '•';
			this.fixed1.Add(this.txtcategory);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtcategory]));
			w4.X = 125;
			w4.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtmodel = new global::Gtk.Entry();
			this.txtmodel.CanFocus = true;
			this.txtmodel.Name = "txtmodel";
			this.txtmodel.IsEditable = true;
			this.txtmodel.InvisibleChar = '•';
			this.fixed1.Add(this.txtmodel);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtmodel]));
			w5.X = 125;
			w5.Y = 110;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Marca:");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w6.X = 35;
			w6.Y = 165;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtbrand = new global::Gtk.Entry();
			this.txtbrand.CanFocus = true;
			this.txtbrand.Name = "txtbrand";
			this.txtbrand.IsEditable = true;
			this.txtbrand.InvisibleChar = '•';
			this.fixed1.Add(this.txtbrand);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtbrand]));
			w7.X = 125;
			w7.Y = 160;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Placa:");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w8.X = 344;
			w8.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtplate = new global::Gtk.Entry();
			this.txtplate.CanFocus = true;
			this.txtplate.Name = "txtplate";
			this.txtplate.IsEditable = true;
			this.txtplate.InvisibleChar = '•';
			this.fixed1.Add(this.txtplate);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtplate]));
			w9.X = 416;
			w9.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtcolor = new global::Gtk.Entry();
			this.txtcolor.CanFocus = true;
			this.txtcolor.Name = "txtcolor";
			this.txtcolor.IsEditable = true;
			this.txtcolor.InvisibleChar = '•';
			this.fixed1.Add(this.txtcolor);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtcolor]));
			w10.X = 416;
			w10.Y = 110;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Color:");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w11.X = 345;
			w11.Y = 115;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Estado:");
			this.fixed1.Add(this.label7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
			w12.X = 345;
			w12.Y = 157;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.statecombo = global::Gtk.ComboBox.NewText();
			this.statecombo.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.statecombo.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.statecombo.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.statecombo.WidthRequest = 100;
			this.statecombo.Name = "statecombo";
			this.statecombo.Active = 0;
			this.fixed1.Add(this.statecombo);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.statecombo]));
			w13.X = 417;
			w13.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtbuscar = new global::Gtk.Entry();
			this.txtbuscar.WidthRequest = 500;
			this.txtbuscar.CanFocus = true;
			this.txtbuscar.Name = "txtbuscar";
			this.txtbuscar.IsEditable = true;
			this.txtbuscar.InvisibleChar = '•';
			this.fixed1.Add(this.txtbuscar);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtbuscar]));
			w14.X = 20;
			w14.Y = 227;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 80;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w15.X = 536;
			w15.Y = 224;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 600;
			this.GtkScrolledWindow.HeightRequest = 400;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.vehitreeview = new global::Gtk.TreeView();
			this.vehitreeview.CanFocus = true;
			this.vehitreeview.Name = "vehitreeview";
			this.GtkScrolledWindow.Add(this.vehitreeview);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w17.X = 21;
			w17.Y = 285;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w18.X = 379;
			w18.Y = 191;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.button3);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
			w19.X = 471;
			w19.Y = 191;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.button4);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
			w20.X = 563;
			w20.Y = 192;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.button5);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
			w21.X = 284;
			w21.Y = 193;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Reiniciar Tabla");
			this.fixed1.Add(this.button6);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
			w22.X = 262;
			w22.Y = 694;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 679;
			this.DefaultHeight = 723;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
			this.vehitreeview.CursorChanged += new global::System.EventHandler(this.OnTvwVehicleCursorChanged);
			this.button3.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.button4.Clicked += new global::System.EventHandler(this.onClickBtnClean);
			this.button5.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.button6.Clicked += new global::System.EventHandler(this.RestartTable);
		}
	}
}
