
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class ModifyCourse
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trwCourse;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.Entry txtdes;

		private global::Gtk.Entry txtname;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.ModifyCourse
			this.Name = "escuela_manejo.Main_forms.ModifyCourse";
			this.Title = global::Mono.Unix.Catalog.GetString("ModifyCourse");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.ModifyCourse.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 360;
			this.GtkScrolledWindow.HeightRequest = 240;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trwCourse = new global::Gtk.TreeView();
			this.trwCourse.CanFocus = true;
			this.trwCourse.Name = "trwCourse";
			this.GtkScrolledWindow.Add(this.trwCourse);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w2.X = 20;
			w2.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w3.X = 47;
			w3.Y = 354;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w4.X = 261;
			w4.Y = 353;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtdes = new global::Gtk.Entry();
			this.txtdes.CanFocus = true;
			this.txtdes.Name = "txtdes";
			this.txtdes.IsEditable = true;
			this.txtdes.InvisibleChar = '•';
			this.fixed1.Add(this.txtdes);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtdes]));
			w5.X = 210;
			w5.Y = 42;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtname = new global::Gtk.Entry();
			this.txtname.CanFocus = true;
			this.txtname.Name = "txtname";
			this.txtname.IsEditable = true;
			this.txtname.InvisibleChar = '•';
			this.fixed1.Add(this.txtname);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtname]));
			w6.X = 17;
			w6.Y = 42;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 423;
			this.DefaultHeight = 400;
			this.Show();
			this.trwCourse.CursorChanged += new global::System.EventHandler(this.OnTvwUsuariosCursorChanged);
			this.button1.Clicked += new global::System.EventHandler(this.OnBtnActualizarClicked);
			this.button2.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
		}
	}
}
