
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Main_forms
{
	public partial class ModifyService
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtname;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtprice;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtstate;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView TrwModifyService;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Main_forms.ModifyService
			this.Name = "escuela_manejo.Main_forms.ModifyService";
			this.Title = global::Mono.Unix.Catalog.GetString("ModifyService");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child escuela_manejo.Main_forms.ModifyService.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 46;
			w1.Y = 21;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtname = new global::Gtk.Entry();
			this.txtname.CanFocus = true;
			this.txtname.Name = "txtname";
			this.txtname.IsEditable = true;
			this.txtname.InvisibleChar = '•';
			this.fixed1.Add(this.txtname);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtname]));
			w2.X = 116;
			w2.Y = 16;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Precio");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w3.X = 48;
			w3.Y = 72;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtprice = new global::Gtk.Entry();
			this.txtprice.CanFocus = true;
			this.txtprice.Name = "txtprice";
			this.txtprice.IsEditable = true;
			this.txtprice.InvisibleChar = '•';
			this.fixed1.Add(this.txtprice);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtprice]));
			w4.X = 116;
			w4.Y = 63;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = "Estado";
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w5.X = 49;
			w5.Y = 126;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtstate = new global::Gtk.Entry();
			this.txtstate.CanFocus = true;
			this.txtstate.Name = "txtstate";
			this.txtstate.IsEditable = true;
			this.txtstate.InvisibleChar = '•';
			this.fixed1.Add(this.txtstate);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtstate]));
			w6.X = 116;
			w6.Y = 117;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w7.X = 95;
			w7.Y = 436;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w8.X = 365;
			w8.Y = 435;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 500;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TrwModifyService = new global::Gtk.TreeView();
			this.TrwModifyService.WidthRequest = 400;
			this.TrwModifyService.HeightRequest = 200;
			this.TrwModifyService.CanFocus = true;
			this.TrwModifyService.Name = "TrwModifyService";
			this.GtkScrolledWindow.Add(this.TrwModifyService);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w10.X = 52;
			w10.Y = 181;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 731;
			this.DefaultHeight = 3481;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.OnBtnActualizarClicked);
			this.button2.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.TrwModifyService.CursorChanged += new global::System.EventHandler(this.OnTvwUsuariosCursorChanged);
		}
	}
}
