
// This file has been generated by the GUI designer. Do not modify.
namespace escuela_manejo.Security_forms
{
	public partial class UserFo
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget escuela_manejo.Security_forms.UserFo
			this.Name = "escuela_manejo.Security_forms.UserFo";
			this.Title = global::Mono.Unix.Catalog.GetString("UserFo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
