
// This file has been generated by the GUI designer. Do not modify.
namespace drive
{
	public partial class Payment
	{
		private global::Gtk.Fixed fixed5;

		private global::Gtk.Label lblServiceType;

		private global::Gtk.Label lblPayment;

		private global::Gtk.ComboBox cmbServiceType;

		private global::Gtk.ComboBox cmbMethod;

		private global::Gtk.Label lblMethod;

		private global::Gtk.Button btnPay;

		private global::Gtk.Label lblSubtotal;

		private global::Gtk.Label lblTotalDollar;

		private global::Gtk.Label lblSubtotalValue;

		private global::Gtk.Label lblTotal;

		private global::Gtk.Label lblSubtotalDollar;

		private global::Gtk.Label lblTotalValue;

		private global::Gtk.Button btnAddCustomer;

		private global::Gtk.Label lblCustomer;

		private global::Gtk.Button btnClean;

		private global::Gtk.Button btnPayCourseService;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trwPayments;

		private global::Gtk.ComboBox cmbClient;

		private global::Gtk.Label lblDate;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget drive.Payment
			this.Name = "drive.Payment";
			this.Title = global::Mono.Unix.Catalog.GetString("Payment");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child drive.Payment.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblServiceType = new global::Gtk.Label();
			this.lblServiceType.Name = "lblServiceType";
			this.lblServiceType.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo de Servicio");
			this.fixed5.Add(this.lblServiceType);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblServiceType]));
			w1.X = 28;
			w1.Y = 114;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblPayment = new global::Gtk.Label();
			this.lblPayment.Name = "lblPayment";
			this.lblPayment.LabelProp = global::Mono.Unix.Catalog.GetString("Factura");
			this.fixed5.Add(this.lblPayment);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblPayment]));
			w2.X = 35;
			w2.Y = 35;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cmbServiceType = global::Gtk.ComboBox.NewText();
			this.cmbServiceType.Name = "cmbServiceType";
			this.fixed5.Add(this.cmbServiceType);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.cmbServiceType]));
			w3.X = 145;
			w3.Y = 108;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cmbMethod = global::Gtk.ComboBox.NewText();
			this.cmbMethod.AppendText(global::Mono.Unix.Catalog.GetString("Seleccione..."));
			this.cmbMethod.AppendText(global::Mono.Unix.Catalog.GetString("Card"));
			this.cmbMethod.AppendText(global::Mono.Unix.Catalog.GetString("Cash"));
			this.cmbMethod.Name = "cmbMethod";
			this.fixed5.Add(this.cmbMethod);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.cmbMethod]));
			w4.X = 171;
			w4.Y = 579;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblMethod = new global::Gtk.Label();
			this.lblMethod.Name = "lblMethod";
			this.lblMethod.LabelProp = global::Mono.Unix.Catalog.GetString("Forma de pago");
			this.fixed5.Add(this.lblMethod);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblMethod]));
			w5.X = 49;
			w5.Y = 584;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnPay = new global::Gtk.Button();
			this.btnPay.CanFocus = true;
			this.btnPay.Name = "btnPay";
			this.btnPay.UseUnderline = true;
			this.btnPay.Label = global::Mono.Unix.Catalog.GetString("Pagar Todo");
			this.fixed5.Add(this.btnPay);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnPay]));
			w6.X = 395;
			w6.Y = 580;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblSubtotal = new global::Gtk.Label();
			this.lblSubtotal.Name = "lblSubtotal";
			this.lblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString("Subtotal");
			this.fixed5.Add(this.lblSubtotal);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblSubtotal]));
			w7.X = 71;
			w7.Y = 489;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblTotalDollar = new global::Gtk.Label();
			this.lblTotalDollar.Name = "lblTotalDollar";
			this.lblTotalDollar.LabelProp = global::Mono.Unix.Catalog.GetString("$");
			this.fixed5.Add(this.lblTotalDollar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblTotalDollar]));
			w8.X = 145;
			w8.Y = 489;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblSubtotalValue = new global::Gtk.Label();
			this.lblSubtotalValue.Name = "lblSubtotalValue";
			this.lblSubtotalValue.LabelProp = global::Mono.Unix.Catalog.GetString("0.0");
			this.fixed5.Add(this.lblSubtotalValue);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblSubtotalValue]));
			w9.X = 165;
			w9.Y = 489;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblTotal = new global::Gtk.Label();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString("Total");
			this.fixed5.Add(this.lblTotal);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblTotal]));
			w10.X = 86;
			w10.Y = 525;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblSubtotalDollar = new global::Gtk.Label();
			this.lblSubtotalDollar.Name = "lblSubtotalDollar";
			this.lblSubtotalDollar.LabelProp = global::Mono.Unix.Catalog.GetString("$");
			this.fixed5.Add(this.lblSubtotalDollar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblSubtotalDollar]));
			w11.X = 145;
			w11.Y = 525;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblTotalValue = new global::Gtk.Label();
			this.lblTotalValue.Name = "lblTotalValue";
			this.lblTotalValue.LabelProp = global::Mono.Unix.Catalog.GetString("0.0");
			this.fixed5.Add(this.lblTotalValue);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblTotalValue]));
			w12.X = 165;
			w12.Y = 525;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnAddCustomer = new global::Gtk.Button();
			this.btnAddCustomer.CanFocus = true;
			this.btnAddCustomer.Name = "btnAddCustomer";
			this.btnAddCustomer.UseUnderline = true;
			this.btnAddCustomer.Label = global::Mono.Unix.Catalog.GetString("Agregar Cliente");
			this.fixed5.Add(this.btnAddCustomer);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnAddCustomer]));
			w13.X = 381;
			w13.Y = 407;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblCustomer = new global::Gtk.Label();
			this.lblCustomer.Name = "lblCustomer";
			this.lblCustomer.LabelProp = global::Mono.Unix.Catalog.GetString("Cliente");
			this.fixed5.Add(this.lblCustomer);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblCustomer]));
			w14.X = 79;
			w14.Y = 414;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnClean = new global::Gtk.Button();
			this.btnClean.CanFocus = true;
			this.btnClean.Name = "btnClean";
			this.btnClean.UseUnderline = true;
			this.btnClean.Label = global::Mono.Unix.Catalog.GetString("Limpiar Campos");
			this.fixed5.Add(this.btnClean);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnClean]));
			w15.X = 535;
			w15.Y = 233;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnPayCourseService = new global::Gtk.Button();
			this.btnPayCourseService.CanFocus = true;
			this.btnPayCourseService.Name = "btnPayCourseService";
			this.btnPayCourseService.UseUnderline = true;
			this.btnPayCourseService.Label = global::Mono.Unix.Catalog.GetString("Agregar a Pago");
			this.fixed5.Add(this.btnPayCourseService);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnPayCourseService]));
			w16.X = 384;
			w16.Y = 110;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trwPayments = new global::Gtk.TreeView();
			this.trwPayments.WidthRequest = 455;
			this.trwPayments.HeightRequest = 152;
			this.trwPayments.CanFocus = true;
			this.trwPayments.Name = "trwPayments";
			this.GtkScrolledWindow.Add(this.trwPayments);
			this.fixed5.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.GtkScrolledWindow]));
			w18.X = 36;
			w18.Y = 175;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cmbClient = global::Gtk.ComboBox.NewText();
			this.cmbClient.Name = "cmbClient";
			this.fixed5.Add(this.cmbClient);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.cmbClient]));
			w19.X = 176;
			w19.Y = 407;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblDate = new global::Gtk.Label();
			this.lblDate.Name = "lblDate";
			this.lblDate.LabelProp = global::Mono.Unix.Catalog.GetString("25/09/00");
			this.fixed5.Add(this.lblDate);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblDate]));
			w20.X = 500;
			w20.Y = 35;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 689;
			this.DefaultHeight = 649;
			this.Show();
			this.cmbMethod.Changed += new global::System.EventHandler(this.onCmbMethodChange);
			this.btnPay.Clicked += new global::System.EventHandler(this.onClickBtnPay);
			this.btnAddCustomer.Clicked += new global::System.EventHandler(this.onClickBtnAddCustomer);
			this.btnClean.Clicked += new global::System.EventHandler(this.onClickBtnClean);
			this.btnPayCourseService.Clicked += new global::System.EventHandler(this.onClickBtnPayCourseService);
		}
	}
}
