
// This file has been generated by the GUI designer. Do not modify.
namespace drive
{
	public partial class CashPayment
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblCashPayment;

		private global::Gtk.Label lblTotalPayment;

		private global::Gtk.Label lblTotalDollar;

		private global::Gtk.Label lblTotalValue;

		private global::Gtk.Entry entAmount;

		private global::Gtk.Label lblAmount;

		private global::Gtk.Label lblChange;

		private global::Gtk.Label lblChangeDollar;

		private global::Gtk.Label lblChangeValue;

		private global::Gtk.Button btnPayCash;

		private global::Gtk.Button btnAddMoney;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget drive.CashPayment
			this.Name = "drive.CashPayment";
			this.Title = global::Mono.Unix.Catalog.GetString("CashPayment");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child drive.CashPayment.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblCashPayment = new global::Gtk.Label();
			this.lblCashPayment.Name = "lblCashPayment";
			this.lblCashPayment.LabelProp = global::Mono.Unix.Catalog.GetString("Pago en Efectivo");
			this.fixed1.Add(this.lblCashPayment);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblCashPayment]));
			w1.X = 147;
			w1.Y = 20;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblTotalPayment = new global::Gtk.Label();
			this.lblTotalPayment.Name = "lblTotalPayment";
			this.lblTotalPayment.LabelProp = global::Mono.Unix.Catalog.GetString("Total a Pagar");
			this.fixed1.Add(this.lblTotalPayment);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblTotalPayment]));
			w2.X = 25;
			w2.Y = 72;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblTotalDollar = new global::Gtk.Label();
			this.lblTotalDollar.Name = "lblTotalDollar";
			this.lblTotalDollar.LabelProp = global::Mono.Unix.Catalog.GetString("$");
			this.fixed1.Add(this.lblTotalDollar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblTotalDollar]));
			w3.X = 133;
			w3.Y = 72;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblTotalValue = new global::Gtk.Label();
			this.lblTotalValue.Name = "lblTotalValue";
			this.lblTotalValue.LabelProp = global::Mono.Unix.Catalog.GetString("0.0");
			this.fixed1.Add(this.lblTotalValue);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblTotalValue]));
			w4.X = 152;
			w4.Y = 72;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entAmount = new global::Gtk.Entry();
			this.entAmount.CanFocus = true;
			this.entAmount.Name = "entAmount";
			this.entAmount.IsEditable = true;
			this.entAmount.InvisibleChar = '•';
			this.fixed1.Add(this.entAmount);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entAmount]));
			w5.X = 130;
			w5.Y = 106;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblAmount = new global::Gtk.Label();
			this.lblAmount.Name = "lblAmount";
			this.lblAmount.LabelProp = global::Mono.Unix.Catalog.GetString("Pago");
			this.fixed1.Add(this.lblAmount);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblAmount]));
			w6.X = 76;
			w6.Y = 110;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblChange = new global::Gtk.Label();
			this.lblChange.Name = "lblChange";
			this.lblChange.LabelProp = global::Mono.Unix.Catalog.GetString("Cambio");
			this.fixed1.Add(this.lblChange);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblChange]));
			w7.X = 60;
			w7.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblChangeDollar = new global::Gtk.Label();
			this.lblChangeDollar.Name = "lblChangeDollar";
			this.lblChangeDollar.LabelProp = global::Mono.Unix.Catalog.GetString("$");
			this.fixed1.Add(this.lblChangeDollar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblChangeDollar]));
			w8.X = 132;
			w8.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblChangeValue = new global::Gtk.Label();
			this.lblChangeValue.Name = "lblChangeValue";
			this.lblChangeValue.LabelProp = global::Mono.Unix.Catalog.GetString("0.0");
			this.fixed1.Add(this.lblChangeValue);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblChangeValue]));
			w9.X = 151;
			w9.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnPayCash = new global::Gtk.Button();
			this.btnPayCash.CanFocus = true;
			this.btnPayCash.Name = "btnPayCash";
			this.btnPayCash.UseUnderline = true;
			this.btnPayCash.Label = global::Mono.Unix.Catalog.GetString("Pagar");
			this.fixed1.Add(this.btnPayCash);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnPayCash]));
			w10.X = 181;
			w10.Y = 201;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAddMoney = new global::Gtk.Button();
			this.btnAddMoney.CanFocus = true;
			this.btnAddMoney.Name = "btnAddMoney";
			this.btnAddMoney.UseUnderline = true;
			this.btnAddMoney.Label = global::Mono.Unix.Catalog.GetString("Depositar...");
			this.fixed1.Add(this.btnAddMoney);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAddMoney]));
			w11.X = 301;
			w11.Y = 105;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 425;
			this.DefaultHeight = 251;
			this.Show();
			this.btnPayCash.Clicked += new global::System.EventHandler(this.onClickBtnPayCash);
			this.btnAddMoney.Clicked += new global::System.EventHandler(this.onClickBtnAddMoney);
		}
	}
}
