
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed4;

	private global::Gtk.Button btnPayment;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnPayment = new global::Gtk.Button();
		this.btnPayment.CanFocus = true;
		this.btnPayment.Name = "btnPayment";
		this.btnPayment.UseUnderline = true;
		this.btnPayment.Label = global::Mono.Unix.Catalog.GetString("Payment");
		this.fixed4.Add(this.btnPayment);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnPayment]));
		w1.X = 235;
		w1.Y = 115;
		this.Add(this.fixed4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 560;
		this.DefaultHeight = 433;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnPayment.Clicked += new global::System.EventHandler(this.onClickBtnPayment);
	}
}
