
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action MenuAction;

	private global::Gtk.Action SalirAction;

	private global::Gtk.Action SeguridadAction;

	private global::Gtk.Action GestionDeUsuariosAction;

	private global::Gtk.Action GestionDeRolesAction;

	private global::Gtk.Action GestionDeOpcionesAction;

	private global::Gtk.Action ControlDeUsuariosAction;

	private global::Gtk.Action ControlDeRolesAction;

	private global::Gtk.Action ControlDeOpcionesAction;

	private global::Gtk.Action AsignarOpcionesARolAction;

	private global::Gtk.Action AsignarRolAUsuariosAction;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.MenuBar menubar2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.MenuAction = new global::Gtk.Action("MenuAction", global::Mono.Unix.Catalog.GetString("Menu"), null, null);
		this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menu");
		w1.Add(this.MenuAction, null);
		this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
		w1.Add(this.SalirAction, null);
		this.SeguridadAction = new global::Gtk.Action("SeguridadAction", global::Mono.Unix.Catalog.GetString("Seguridad"), null, null);
		this.SeguridadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Seguridad");
		w1.Add(this.SeguridadAction, null);
		this.GestionDeUsuariosAction = new global::Gtk.Action("GestionDeUsuariosAction", global::Mono.Unix.Catalog.GetString("Gestion de Usuarios"), null, null);
		this.GestionDeUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Usuarios");
		w1.Add(this.GestionDeUsuariosAction, null);
		this.GestionDeRolesAction = new global::Gtk.Action("GestionDeRolesAction", global::Mono.Unix.Catalog.GetString("Gestion de Roles"), null, null);
		this.GestionDeRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Roles");
		w1.Add(this.GestionDeRolesAction, null);
		this.GestionDeOpcionesAction = new global::Gtk.Action("GestionDeOpcionesAction", global::Mono.Unix.Catalog.GetString("Gestion de Opciones"), null, null);
		this.GestionDeOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Opciones");
		w1.Add(this.GestionDeOpcionesAction, null);
		this.ControlDeUsuariosAction = new global::Gtk.Action("ControlDeUsuariosAction", global::Mono.Unix.Catalog.GetString("Control de Usuarios"), null, null);
		this.ControlDeUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de Usuarios");
		w1.Add(this.ControlDeUsuariosAction, null);
		this.ControlDeRolesAction = new global::Gtk.Action("ControlDeRolesAction", global::Mono.Unix.Catalog.GetString("Control de Roles"), null, null);
		this.ControlDeRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de Roles");
		w1.Add(this.ControlDeRolesAction, null);
		this.ControlDeOpcionesAction = new global::Gtk.Action("ControlDeOpcionesAction", global::Mono.Unix.Catalog.GetString("Control de opciones"), null, null);
		this.ControlDeOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de opciones");
		w1.Add(this.ControlDeOpcionesAction, null);
		this.AsignarOpcionesARolAction = new global::Gtk.Action("AsignarOpcionesARolAction", global::Mono.Unix.Catalog.GetString("Asignar opciones a rol"), null, null);
		this.AsignarOpcionesARolAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar opciones a rol");
		w1.Add(this.AsignarOpcionesARolAction, null);
		this.AsignarRolAUsuariosAction = new global::Gtk.Action("AsignarRolAUsuariosAction", global::Mono.Unix.Catalog.GetString("Asignar Rol a Usuarios"), null, null);
		this.AsignarRolAUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar Rol a Usuarios");
		w1.Add(this.AsignarRolAUsuariosAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 900;
		this.HeightRequest = 540;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 900;
		this.DefaultHeight = 540;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='MenuAction' action='MenuAction'><menuitem name='SalirAction' action='SalirAction'/></menu><menu name='SeguridadAction' action='SeguridadAction'><menu name='GestionDeUsuariosAction' action='GestionDeUsuariosAction'><menuitem name='ControlDeUsuariosAction' action='ControlDeUsuariosAction'/></menu><menu name='GestionDeRolesAction' action='GestionDeRolesAction'><menuitem name='ControlDeRolesAction' action='ControlDeRolesAction'/><menuitem name='AsignarRolAUsuariosAction' action='AsignarRolAUsuariosAction'/></menu><menu name='GestionDeOpcionesAction' action='GestionDeOpcionesAction'><menuitem name='ControlDeOpcionesAction' action='ControlDeOpcionesAction'/><menuitem name='AsignarOpcionesARolAction' action='AsignarOpcionesARolAction'/></menu></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.fixed2.Add(this.menubar2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.menubar2]));
		w2.X = 6;
		w2.Y = 7;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SalirAction.Activated += new global::System.EventHandler(this.onSalirActionActivated);
		this.ControlDeUsuariosAction.Activated += new global::System.EventHandler(this.onControlDeUsuarios);
	}
}
