
// This file has been generated by the GUI designer. Do not modify.
namespace users.Forms
{
	public partial class ClientF
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Frame frame12;

		private global::Gtk.Table table10;

		private global::Gtk.Button button2;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Button button5;

		private global::Gtk.Button button6;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.TreeView treeview5;

		private global::Gtk.Frame frame8;

		private global::Gtk.Table table6;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.Entry entry10;

		private global::Gtk.Entry entry11;

		private global::Gtk.Entry entry12;

		private global::Gtk.Entry entry7;

		private global::Gtk.Entry entry8;

		private global::Gtk.Entry entry9;

		private global::Gtk.Label label17;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label GtkLabel7;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget users.Forms.ClientF
			this.Name = "users.Forms.ClientF";
			this.Title = global::Mono.Unix.Catalog.GetString("Formulario Cliente");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child users.Forms.ClientF.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.frame12 = new global::Gtk.Frame();
			this.frame12.WidthRequest = 800;
			this.frame12.HeightRequest = 396;
			this.frame12.CanFocus = true;
			this.frame12.Name = "frame12";
			this.frame12.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame12.Gtk.Container+ContainerChild
			this.table10 = new global::Gtk.Table(((uint)(1)), ((uint)(5)), false);
			this.table10.Name = "table10";
			this.table10.RowSpacing = ((uint)(8));
			this.table10.ColumnSpacing = ((uint)(8));
			// Container child table10.Gtk.Table+TableChild
			this.button2 = new global::Gtk.Button();
			this.button2.WidthRequest = 80;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.table10.Add(this.button2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table10[this.button2]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table10.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button();
			this.button3.WidthRequest = 80;
			this.button3.HeightRequest = 15;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.table10.Add(this.button3);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table10[this.button3]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table10.Gtk.Table+TableChild
			this.button4 = new global::Gtk.Button();
			this.button4.WidthRequest = 80;
			this.button4.HeightRequest = 15;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.table10.Add(this.button4);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table10[this.button4]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table10.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button();
			this.button5.WidthRequest = 80;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.table10.Add(this.button5);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table10[this.button5]));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table10.Gtk.Table+TableChild
			this.button6 = new global::Gtk.Button();
			this.button6.WidthRequest = 80;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Mostrar");
			this.table10.Add(this.button6);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table10[this.button6]));
			w5.LeftAttach = ((uint)(4));
			w5.RightAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.frame12.Add(this.table10);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b></b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame12.LabelWidget = this.GtkLabel6;
			this.fixed3.Add(this.frame12);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame12]));
			w7.Y = 162;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.treeview5 = new global::Gtk.TreeView();
			this.treeview5.WidthRequest = 750;
			this.treeview5.HeightRequest = 330;
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.fixed3.Add(this.treeview5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.treeview5]));
			w8.X = 30;
			w8.Y = 218;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.WidthRequest = 700;
			this.frame8.HeightRequest = 150;
			this.frame8.CanFocus = true;
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame8.Gtk.Container+ContainerChild
			this.table6 = new global::Gtk.Table(((uint)(4)), ((uint)(4)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.Name = "combobox2";
			this.table6.Add(this.combobox2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table6[this.combobox2]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.table6.Add(this.entry10);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table6[this.entry10]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry11 = new global::Gtk.Entry();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.table6.Add(this.entry11);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table6[this.entry11]));
			w11.LeftAttach = ((uint)(3));
			w11.RightAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry12 = new global::Gtk.Entry();
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '•';
			this.table6.Add(this.entry12);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table6[this.entry12]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(3));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.table6.Add(this.entry7);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table6[this.entry7]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.table6.Add(this.entry8);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table6[this.entry8]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.table6.Add(this.entry9);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table6[this.entry9]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres");
			this.table6.Add(this.label17);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table6[this.label17]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.table6.Add(this.label18);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table6[this.label18]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Correo");
			this.table6.Add(this.label19);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table6[this.label19]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
			this.table6.Add(this.label20);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table6[this.label20]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion ");
			this.table6.Add(this.label21);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table6[this.label21]));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula");
			this.table6.Add(this.label22);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table6[this.label22]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.table6.Add(this.label23);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table6[this.label23]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.frame8.Add(this.table6);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Datos personales</b>");
			this.GtkLabel7.UseMarkup = true;
			this.GtkLabel7.Justify = ((global::Gtk.Justification)(2));
			this.frame8.LabelWidget = this.GtkLabel7;
			this.fixed3.Add(this.frame8);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame8]));
			w24.X = 5;
			w24.Y = 8;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 807;
			this.DefaultHeight = 567;
			this.Show();
		}
	}
}
