
// This file has been generated by the GUI designer. Do not modify.
namespace Escuela_Manejo1
{
	public partial class Frm_Clientes
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Frame frame5;

		private global::Gtk.Table table4;

		private global::Gtk.Label correoc;

		private global::Gtk.Label id;

		private global::Gtk.Label label10;

		private global::Gtk.Label NombreC;

		private global::Gtk.Entry txtapellidoc;

		private global::Gtk.Entry txtcorreoc;

		private global::Gtk.Entry txtidc;

		private global::Gtk.Entry txtnombrec;

		private global::Gtk.Label GtkLabel;

		private global::Gtk.Frame frame2;

		private global::Gtk.Table table2;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtdireccionc;

		private global::Gtk.Entry txttelefonoc;

		private global::Gtk.Label GtkLabel8;

		private global::Gtk.Frame frame7;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Table table6;

		private global::Gtk.Button btnEditar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnNuevo;

		private global::Gtk.Table table7;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Entry txtbuscar;

		private global::Gtk.TreeView trwtabla;

		private global::Gtk.Label GtkLabel6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Escuela_Manejo1.Frm_Clientes
			this.Name = "Escuela_Manejo1.Frm_Clientes";
			this.Title = global::Mono.Unix.Catalog.GetString("Frm_Clientes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Escuela_Manejo1.Frm_Clientes.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.WidthRequest = 371;
			this.frame5.HeightRequest = 150;
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame5.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.correoc = new global::Gtk.Label();
			this.correoc.Name = "correoc";
			this.correoc.LabelProp = global::Mono.Unix.Catalog.GetString("Correo");
			this.table4.Add(this.correoc);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4[this.correoc]));
			w1.TopAttach = ((uint)(3));
			w1.BottomAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.id = new global::Gtk.Label();
			this.id.Name = "id";
			this.id.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.table4.Add(this.id);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4[this.id]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.table4.Add(this.label10);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4[this.label10]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.NombreC = new global::Gtk.Label();
			this.NombreC.Name = "NombreC";
			this.NombreC.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.table4.Add(this.NombreC);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4[this.NombreC]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.txtapellidoc = new global::Gtk.Entry();
			this.txtapellidoc.CanFocus = true;
			this.txtapellidoc.Name = "txtapellidoc";
			this.txtapellidoc.IsEditable = true;
			this.txtapellidoc.InvisibleChar = '•';
			this.table4.Add(this.txtapellidoc);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.txtapellidoc]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.txtcorreoc = new global::Gtk.Entry();
			this.txtcorreoc.CanFocus = true;
			this.txtcorreoc.Name = "txtcorreoc";
			this.txtcorreoc.IsEditable = true;
			this.txtcorreoc.InvisibleChar = '•';
			this.table4.Add(this.txtcorreoc);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4[this.txtcorreoc]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.txtidc = new global::Gtk.Entry();
			this.txtidc.WidthRequest = 11;
			this.txtidc.CanFocus = true;
			this.txtidc.Name = "txtidc";
			this.txtidc.IsEditable = true;
			this.txtidc.InvisibleChar = '•';
			this.table4.Add(this.txtidc);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4[this.txtidc]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.txtnombrec = new global::Gtk.Entry();
			this.txtnombrec.CanFocus = true;
			this.txtnombrec.Name = "txtnombrec";
			this.txtnombrec.IsEditable = true;
			this.txtnombrec.InvisibleChar = '•';
			this.table4.Add(this.txtnombrec);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4[this.txtnombrec]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.frame5.Add(this.table4);
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Datos Personales</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel;
			this.fixed3.Add(this.frame5);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame5]));
			w10.X = -1;
			w10.Y = 5;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.WidthRequest = 371;
			this.frame2.HeightRequest = 94;
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion");
			this.table2.Add(this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.label1]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
			this.table2.Add(this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.label2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtdireccionc = new global::Gtk.Entry();
			this.txtdireccionc.CanFocus = true;
			this.txtdireccionc.Name = "txtdireccionc";
			this.txtdireccionc.IsEditable = true;
			this.txtdireccionc.InvisibleChar = '•';
			this.table2.Add(this.txtdireccionc);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.txtdireccionc]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txttelefonoc = new global::Gtk.Entry();
			this.txttelefonoc.CanFocus = true;
			this.txttelefonoc.Name = "txttelefonoc";
			this.txttelefonoc.IsEditable = true;
			this.txttelefonoc.InvisibleChar = '•';
			this.table2.Add(this.txttelefonoc);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.txttelefonoc]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.frame2.Add(this.table2);
			this.GtkLabel8 = new global::Gtk.Label();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b></b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel8;
			this.fixed3.Add(this.frame2);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame2]));
			w16.X = 380;
			w16.Y = 8;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.WidthRequest = 900;
			this.frame7.HeightRequest = 411;
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame7.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table6 = new global::Gtk.Table(((uint)(1)), ((uint)(4)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.WidthRequest = 85;
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.table6.Add(this.btnEditar);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table6[this.btnEditar]));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.WidthRequest = 84;
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.table6.Add(this.btnEliminar);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table6[this.btnEliminar]));
			w18.LeftAttach = ((uint)(3));
			w18.RightAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.WidthRequest = 89;
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.table6.Add(this.btnGuardar);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table6[this.btnGuardar]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.WidthRequest = 130;
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Limpiar Campos");
			this.table6.Add(this.btnNuevo);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table6[this.btnNuevo]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table6]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table7 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 82;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.table7.Add(this.btnBuscar);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table7[this.btnBuscar]));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.txtbuscar = new global::Gtk.Entry();
			this.txtbuscar.CanFocus = true;
			this.txtbuscar.Name = "txtbuscar";
			this.txtbuscar.IsEditable = true;
			this.txtbuscar.InvisibleChar = '•';
			this.table7.Add(this.txtbuscar);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table7[this.txtbuscar]));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table7);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table7]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.trwtabla = new global::Gtk.TreeView();
			this.trwtabla.CanFocus = true;
			this.trwtabla.Name = "trwtabla";
			this.vbox1.Add(this.trwtabla);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.trwtabla]));
			w25.Position = 2;
			this.frame7.Add(this.vbox1);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b></b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel6;
			this.fixed3.Add(this.frame7);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame7]));
			w27.X = 200;
			w27.Y = 157;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1294;
			this.DefaultHeight = 701;
			this.Show();
			this.btnNuevo.Clicked += new global::System.EventHandler(this.OnBtnNuevoClicked);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnEditar.Clicked += new global::System.EventHandler(this.OnBtnEditarClicked);
			this.trwtabla.CursorChanged += new global::System.EventHandler(this.OnTrwtablaCursorChanged);
		}
	}
}
