
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action MenuAction;

	private global::Gtk.Action GestionAction;

	private global::Gtk.Action SalirAction;

	private global::Gtk.Action GestionClienteAction;

	private global::Gtk.Action GestionInstructorAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.MenuBar menubar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.MenuAction = new global::Gtk.Action("MenuAction", global::Mono.Unix.Catalog.GetString("Menu"), null, null);
		this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menu");
		w1.Add(this.MenuAction, null);
		this.GestionAction = new global::Gtk.Action("GestionAction", global::Mono.Unix.Catalog.GetString("Gestion"), null, null);
		this.GestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion");
		w1.Add(this.GestionAction, null);
		this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
		w1.Add(this.SalirAction, null);
		this.GestionClienteAction = new global::Gtk.Action("GestionClienteAction", global::Mono.Unix.Catalog.GetString("Gestion Cliente"), null, null);
		this.GestionClienteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion Cliente");
		w1.Add(this.GestionClienteAction, null);
		this.GestionInstructorAction = new global::Gtk.Action("GestionInstructorAction", global::Mono.Unix.Catalog.GetString("Gestion instructor"), null, null);
		this.GestionInstructorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion instructor");
		w1.Add(this.GestionInstructorAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='MenuAction' action='MenuAction'><menuitem name='SalirAction' action='SalirAction'/></menu><menu name='GestionAction' action='GestionAction'><menuitem name='GestionClienteAction' action='GestionClienteAction'/><menuitem name='GestionInstructorAction' action='GestionInstructorAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.CanFocus = true;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add(this.menubar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.menubar1]));
		w2.Y = 4;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 458;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SalirAction.Activated += new global::System.EventHandler(this.OnSalirActionActivated);
		this.GestionClienteAction.Activated += new global::System.EventHandler(this.OnGestionClienteActionActivated);
		this.GestionInstructorAction.Activated += new global::System.EventHandler(this.OnGestionInstructorActionActivated);
	}
}
